### ISSUE TITLE
Add your own relays

### ISSUE THREAD

**Issue by bitkarrot** [nostrband/nostr-login#108]
Is is possible to add relays other than the 3 that are currently used for nostr-login? Would be nice to have a flexible option for people who are on different ones. 

thanks.

**Comment by nostrband** [comment]
Relays are only used to fetch profiles, and we use purplepag.es and user.kindpag.es that supposedly collect all the profiles. So if you specify your own, it would just mean some profiles are likely not there. Or do you have something else in mind?

**Comment by bitkarrot** [comment]
some groups with their own relays might not be on the public ones, that's what i was thinking, its a nice to have but if most people are visible on the relays you have that is fine. I did notice a lot of time outs on the purplepag.es relay though as i was testing it

**Comment by jjim1982** [comment]
I also couldn't find my account on those relays

**Comment by bitkarrot** [comment]
Thank you @nostrband
