### ISSUE TITLE
Unable to approve permission request when widget is blocked by pop-up window

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-login#125]
Precondition: your account shouldn't have permissions to post reactions on selected website
1. Login on the published website through nsec.app (ex. https://leafes47.npub.pro/)
2. Try to post reaction using actions menu 
![Image](https://github.com/user-attachments/assets/0cf2f7cd-b5f6-4105-b0c5-e53bf8b21f87)

expected: pop-up window with permission request is open
actual: permission request is sent, but need to open nsec.app manualy to allow requested permissions

UPD: Now i see there is a request on the login module but its impossible to press while reaction select and postiong reaction pop-up is present (it's blurred and unavaliable to click). So when user try to post reaction he will face endless load on the reaction post.

**Comment by a-fralou** [comment]
Due to the way the dialog works, we can't simply open our own dialog on top of the dialog, as this will block clicks on the document.

We need to learn to detect an already open dialogue and open your own on top of it.

**Comment by leafes** [comment]
@a-fralou, is it possible to trigger a pop-up browser window for a signature request without the user clicking a button in the widget? If so, what problems could this potentially cause?

**Comment by leafes** [comment]
@nostrband now after login <dialog> tag is still active and cover all the elements on the site and make it impossible to interact with a website until a page reload

Steps to reproduce: 
1. Login using login widget
2. Observe that site is covered behind <dialog> tag 

https://jam.dev/c/f8b2d893-3c85-4307-a939-1464384456cd

![Image](https://github.com/user-attachments/assets/ba0e29b5-49e3-40b5-bfa1-6713dc3621c8)

**Comment by nostrband** [comment]
Fixed with nostr-login 1.6.11, please check on the same site.

**Comment by leafes** [comment]
> Fixed with nostr-login 1.6.11, please check on the same site.

The overlay issue has been resolved. I propose closing this issue.
