### ISSUE TITLE
[new.nsec] Missing CORS headers on nostr.json?name= call when submiting signup with new.nsec.app

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-login#128]
https://jam.dev/c/5ba372e5-42be-41b2-8e45-5dad55991933

**Comment by nostrband** [comment]
You were getting 502 bcs server was crashing when nostr-login was sending create_account using the new encryption scheme. Should be fixed now.

**Comment by leafes** [comment]
fixed
