### ISSUE TITLE
Login modal is not updating on safari desktop

### ISSUE THREAD

**Issue by leafes** [nostrband/nostr-login#131]
State of modal window is not updated while signing up using Safari on MacOS

https://drive.google.com/file/d/1ABYjiPnRtp3XcgQ2SXF2niZS6KnvqBOA/view?usp=sharing

**Comment by nostrband** [comment]
Fixed.

**Comment by leafes** [comment]
Retested on Safari. Issue is fixed: modal is closed after signup and auth state is updated
