### ISSUE TITLE
Switch to using query-string for metadata in nostrconnect urls

### ISSUE THREAD

**Issue by nostrband** [nostrband/nostr-login#143]

**Comment by nostrband** [comment]
Published nostr-login 1.6.13, @leafes please check on npub.pro: Connect => Nsec.app (icon, app name etc are shown in nsec.app), Connect => Connection string => paste into nsec.app (icon, app name etc are shown).

**Comment by leafes** [comment]
@nostrband Tested. Connection string works fine. Connection string after nsec.app sign in works fine as well. Tested on desktop + mobile.
